services:
  joyride:
    image: ghcr.io/traefikturkey/joyride:${JOYRIDE_DOCKER_TAG:-serf}
    container_name: ${JOYRIDE_CONTAINER_NAME:-joyride}
    restart: unless-stopped
    environment:
      - HOSTIP=${HOSTIP}
      #- UPSTREAM_DNS=${UPSTREAM_DNS}
      - JOYRIDE_HOSTNAME=${HOSTNAME}
      - JOYRIDE_HOSTNAME_DNS_ENTRY=${JOYRIDE_HOST_DNS_ENTRY:-true}
      - JOYRIDE_NXDOMAIN_ENABLED=${JOYRIDE_NXDOMAIN_ENABLED:-false}
      - JOYRIDE_LOG_DEBUG=${JOYRIDE_LOG_DEBUG:-false}
      - JOYRIDE_LOG_QUERIES=${JOYRIDE_LOG_QUERIES:-false}
      - JOYRIDE_ENABLE_SERF=${JOYRIDE_ENABLE_SERF:-false}
    network_mode: host
    # ports:
    #   - 54:54/udp
    #   - 7946:7946/udp
    #   - 7946:7946/tcp
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:ro
    labels:
      - autoheal=true